// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Widget4x1.tsx": () => import("../components/mockups/Widget4x1.tsx"),
  "./components/mockups/story-directions/Atlas.tsx": () => import("../components/mockups/story-directions/Atlas.tsx"),
  "./components/mockups/story-directions/Current.tsx": () => import("../components/mockups/story-directions/Current.tsx"),
  "./components/mockups/story-directions/Performance.tsx": () => import("../components/mockups/story-directions/Performance.tsx"),
  "./components/mockups/story-directions/Souvenir.tsx": () => import("../components/mockups/story-directions/Souvenir.tsx"),
  "./components/mockups/trip-charts/TripCharts.tsx": () => import("../components/mockups/trip-charts/TripCharts.tsx"),
  "./components/mockups/widget/AddressesPage.tsx": () => import("../components/mockups/widget/AddressesPage.tsx"),
  "./components/mockups/widget/IdeaBCompact.tsx": () => import("../components/mockups/widget/IdeaBCompact.tsx"),
  "./components/mockups/widget/TodoAndroidWidget.tsx": () => import("../components/mockups/widget/TodoAndroidWidget.tsx"),
  "./components/mockups/widget/WidgetApercu.tsx": () => import("../components/mockups/widget/WidgetApercu.tsx"),
  "./components/mockups/widget/YoannWidget.tsx": () => import("../components/mockups/widget/YoannWidget.tsx"),
  "./components/mockups/yoann-indigo/BoldEditorial.tsx": () => import("../components/mockups/yoann-indigo/BoldEditorial.tsx"),
  "./components/mockups/yoann-indigo/FlatAere.tsx": () => import("../components/mockups/yoann-indigo/FlatAere.tsx"),
  "./components/mockups/yoann-indigo/VioletGlass.tsx": () => import("../components/mockups/yoann-indigo/VioletGlass.tsx"),
  "./components/mockups/yoann-redesign/Navigation.tsx": () => import("../components/mockups/yoann-redesign/Navigation.tsx"),
  "./components/mockups/yoann-redesign/Stats.tsx": () => import("../components/mockups/yoann-redesign/Stats.tsx"),
  "./components/mockups/yoann-redesign/Trajets.tsx": () => import("../components/mockups/yoann-redesign/Trajets.tsx"),
  "./components/mockups/yoann-v2/NeonBureau.tsx": () => import("../components/mockups/yoann-v2/NeonBureau.tsx"),
  "./components/mockups/yoann-v2/Tarmac.tsx": () => import("../components/mockups/yoann-v2/Tarmac.tsx"),
  "./components/mockups/yoann-v2/Terrain.tsx": () => import("../components/mockups/yoann-v2/Terrain.tsx")
};
